/**
 * Form behaviors: value collection, validation, submit.
 *
 * This is what makes FormHandle real. The renderer stamps a `<form>` with its
 * declared field names and an optional client-side rules object; these handlers
 * read values back, mark invalid fields, and emit `submitted` with the payload
 * so a browser action receives real data instead of having to scrape the DOM.
 */
export function formBehaviors(): string[] {
  return [
    '// Forms: collect values, apply client-side rules, emit `submitted` with data.',
    'function morganaFormValues(form){',
    '  var out = {};',
    '  var fields = form.querySelectorAll("[name]");',
    '  for(var i=0;i<fields.length;i++){',
    '    var f = fields[i];',
    '    var n = f.getAttribute("name");',
    '    if(!n) continue;',
    '    if(f.type==="checkbox"){ if(f.checked) out[n] = out[n]===undefined ? true : (Array.isArray(out[n])?out[n].concat([true]):[out[n],true]); }',
    '    else if(f.type==="radio"){ if(f.checked) out[n]=f.value; }',
    '    else if(f.type==="number"){ var num=parseFloat(f.value); out[n] = isNaN(num) ? (f.value===""?null:num) : num; }',
    '    else { out[n]=f.value; }',
    '  }',
    '  return out;',
    '}',
    'function morganaFormClearErrors(form){',
    '  var errs = form.querySelectorAll("[data-part=\\"error\\"]");',
    '  for(var i=0;i<errs.length;i++){ errs[i].remove(); }',
    '  var fields = form.querySelectorAll("[aria-invalid=\\"true\\"]");',
    '  for(var j=0;j<fields.length;j++){ fields[j].removeAttribute("aria-invalid"); }',
    '  form.setAttribute("data-valid","true");',
    '}',
    'function morganaFormSetError(form, name, message){',
    '  var field = form.querySelector("[name=\\""+String(name).replace(/"/g,"")+"\\"]");',
    '  if(!field) return;',
    '  field.setAttribute("aria-invalid","true");',
    '  var box = document.createElement("div");',
    '  box.setAttribute("data-part","error");',
    '  box.setAttribute("role","alert");',
    '  box.textContent = message;',
    '  if(field.parentNode) field.parentNode.appendChild(box);',
    '  form.setAttribute("data-valid","false");',
    '}',
    '// Client-side rules: { field: "required" | { required, minLength, maxLength,',
    '// pattern, min, max, email } }. Compiled into data-rules by the renderer.',
    'function morganaFormValidate(form){',
    '  var raw = form.getAttribute("data-rules");',
    '  if(!raw) return true;',
    '  var rules;',
    '  try{ rules = JSON.parse(raw); }catch(e){ return true; }',
    '  morganaFormClearErrors(form);',
    '  var values = morganaFormValues(form);',
    '  var ok = true;',
    '  for(var name in rules){',
    '    if(!Object.prototype.hasOwnProperty.call(rules,name)) continue;',
    '    var rule = rules[name];',
    '    if(typeof rule==="string"){ rule = { required: rule==="required" }; }',
    '    var v = values[name];',
    '    var empty = v===undefined || v===null || v==="";',
    '    if(rule.required && empty){ morganaFormSetError(form,name,rule.message||(name+" is required")); ok=false; continue; }',
    '    if(empty) continue;',
    '    var s = String(v);',
    '    if(rule.minLength && s.length<rule.minLength){ morganaFormSetError(form,name,rule.message||(name+" must be at least "+rule.minLength+" characters")); ok=false; }',
    '    else if(rule.maxLength && s.length>rule.maxLength){ morganaFormSetError(form,name,rule.message||(name+" must be at most "+rule.maxLength+" characters")); ok=false; }',
    '    else if(rule.email && !/^[^@\\s]+@[^@\\s]+\\.[^@\\s]+$/.test(s)){ morganaFormSetError(form,name,rule.message||(name+" must be a valid email")); ok=false; }',
    '    else if(rule.pattern && !new RegExp(rule.pattern).test(s)){ morganaFormSetError(form,name,rule.message||(name+" is not valid")); ok=false; }',
    '    else if(rule.min!==undefined && parseFloat(s)<rule.min){ morganaFormSetError(form,name,rule.message||(name+" must be at least "+rule.min)); ok=false; }',
    '    else if(rule.max!==undefined && parseFloat(s)>rule.max){ morganaFormSetError(form,name,rule.message||(name+" must be at most "+rule.max)); ok=false; }',
    '  }',
    '  return ok;',
    '}',
    'function morganaFormSetSubmitting(form, on){',
    '  form.setAttribute("data-submitting", on?"true":"false");',
    '  var btns = form.querySelectorAll("button[type=\\"submit\\"],[data-part=\\"submit\\"]");',
    '  for(var i=0;i<btns.length;i++){ btns[i].disabled = on; }',
    '}',
    'document.addEventListener("submit", function(e){',
    '  var form = e.target && e.target.closest ? e.target.closest("[data-kind=\\"form\\"],[data-kind=\\"login\\"],[data-kind=\\"signup\\"]") : null;',
    '  if(!form) return;',
    '  e.preventDefault();',
    '  if(form.getAttribute("data-submitting")==="true") return;',
    '  if(!morganaFormValidate(form)){',
    '    dispatchPageEvent("invalid", form.getAttribute("data-entity")||"", form, { values: morganaFormValues(form) });',
    '    return;',
    '  }',
    '  var values = morganaFormValues(form);',
    '  if(form.getAttribute("data-emit-payload")!=="false"){',
    '    var named = form.getAttribute("data-action");',
    '    if(named) dispatchPageEvent(named, form.getAttribute("data-entity")||"", form, values);',
    '    else dispatchPageEvent("submitted", form.getAttribute("data-entity")||"", form, values);',
    '  }',
    '});',
    '// Login/signup dispatch a named event so one handler can tell them apart.',
    'document.addEventListener("click", function(e){',
    '  var sub = e.target && e.target.closest ? e.target.closest("[data-part=\\"submit\\"]") : null;',
    '  if(sub && sub.tagName!=="BUTTON"){ e.preventDefault(); var f=sub.closest("form"); if(f && f.requestSubmit) f.requestSubmit(); }',
    '});',
  ];
}
