/**
 * Overlay behaviors: tabs, dialogs, accordions, dropdowns, tooltips.
 *
 * All four are the same shape — a trigger sets `open`/`active` on a root, and
 * the root's children react. Dialog was the first; the rest reuse its contract
 * so a kind never invents a parallel convention.
 */
export function overlayBehaviors(): string[] {
  return [
    '// Tabs: switch active trigger + panel within the same tab root.',
    'document.addEventListener("click", function(e){',
    '  var tab = e.target && e.target.closest ? e.target.closest("[data-part=\\"tab\\"]") : null;',
    '  if(!tab || tab.getAttribute("data-disabled")==="true") return;',
    '  var root = tab.closest("[data-kind=\\"tabs\\"]");',
    '  if(!root) return;',
    '  var key = tab.getAttribute("data-tab-key");',
    '  var tabs = root.querySelectorAll("[data-part=\\"tab\\"]");',
    '  for(var i=0;i<tabs.length;i++){ if(tabs[i].getAttribute("data-tab-key")===key)tabs[i].setAttribute("data-active","true");else tabs[i].removeAttribute("data-active"); }',
    '  var panels = root.querySelectorAll("[data-part=\\"panel\\"]");',
    '  for(var p=0;p<panels.length;p++){ if(panels[p].getAttribute("data-panel-key")===key)panels[p].removeAttribute("hidden");else panels[p].setAttribute("hidden",""); }',
    '});',
    '// Dialogs: open triggers, overlay/cancel/dismiss close, confirm closes + submits.',
    'document.addEventListener("click", function(e){',
    '  var consumed = false;',
    '  var opener = e.target && e.target.closest ? e.target.closest("[data-open-dialog]") : null;',
    '  if(opener){ var dlg=document.querySelector("[data-entity=\\""+opener.getAttribute("data-open-dialog")+"\\"]"); if(dlg)dlg.style.display="flex"; return; }',
    '  var t = e.target && e.target.closest ? e.target.closest("[data-part=\\"dismiss\\"],[data-part=\\"cancel\\"],[data-part=\\"overlay\\"][data-close=\\"true\\"]") : null;',
    '  if(t){ var d=t.closest("[data-kind=\\"dialog\\"]"); if(d){d.style.display="none";consumed=true;} }',
    '  if(consumed) return;',
    '  var ok = e.target && e.target.closest ? e.target.closest("[data-part=\\"confirm\\"]") : null;',
    '  if(ok){ var dd=ok.closest("[data-kind=\\"dialog\\"]"); if(dd){dd.style.display="none";dispatchPageEvent("submitted",dd.getAttribute("data-entity")||"",dd,e);} return; }',
    '  // Accordion: single-open — opening one item closes its siblings.',
    '  var accTrigger = e.target && e.target.closest ? e.target.closest("[data-part=\\"accordion-trigger\\"]") : null;',
    '  if(accTrigger){',
    '    var acc = accTrigger.closest("[data-kind=\\"accordion\\"]");',
    '    if(acc && accTrigger.getAttribute("data-disabled")!=="true"){',
    '      var key2 = accTrigger.getAttribute("data-item-key");',
    '      var open = accTrigger.getAttribute("data-open")!=="true";',
    '      if(acc.getAttribute("data-multiple")!=="true"){',
    '        var all = acc.querySelectorAll("[data-part=\\"accordion-trigger\\"]");',
    '        for(var a=0;a<all.length;a++){',
    '          all[a].setAttribute("data-open","false");',
    '          var ip = all[a].parentNode ? all[a].parentNode.querySelector("[data-part=\\"accordion-panel\\"]") : null;',
    '          if(ip) ip.setAttribute("hidden","");',
    '        }',
    '      }',
    '      accTrigger.setAttribute("data-open", open?"true":"false");',
    '      var myPanel = accTrigger.parentNode ? accTrigger.parentNode.querySelector("[data-part=\\"accordion-panel\\"]") : null;',
    '      if(myPanel){ if(open) myPanel.removeAttribute("hidden"); else myPanel.setAttribute("hidden",""); }',
    '    }',
    '    return;',
    '  }',
    '  // Dropdown / menu: trigger toggles its panel; outside click closes.',
    '  var ddTrigger = e.target && e.target.closest ? e.target.closest("[data-part=\\"dropdown-trigger\\"]") : null;',
    '  if(ddTrigger){',
    '    var dd = ddTrigger.closest("[data-kind=\\"dropdown\\"],[data-kind=\\"menu\\"]");',
    '    if(dd && ddTrigger.getAttribute("data-disabled")!=="true"){',
    '      var willOpen = dd.getAttribute("data-open")!=="true";',
    '      closeAllDropdowns(ddTrigger);',
    '      dd.setAttribute("data-open", willOpen?"true":"false");',
    '      var ddPanel = dd.querySelector("[data-part=\\"dropdown-panel\\"]");',
    '      if(ddPanel){ if(willOpen) ddPanel.removeAttribute("hidden"); else ddPanel.setAttribute("hidden",""); }',
    '    }',
    '    return;',
    '  }',
    '  // A click outside any open dropdown/menu closes it.',
    '  if(!(e.target && e.target.closest && e.target.closest("[data-kind=\\"dropdown\\"],[data-kind=\\"menu\\"]"))){',
    '    closeAllDropdowns(null);',
    '  }',
    '  var sel = e.target && e.target.closest ? e.target.closest("[data-part=\\"dropdown-item\\"]") : null;',
    '  if(sel){',
    '    var dsel = sel.closest("[data-kind=\\"dropdown\\"],[data-kind=\\"menu\\"]");',
    '    if(dsel && dsel.getAttribute("data-close-on-select")==="true"){ dsel.setAttribute("data-open","false"); var sp=dsel.querySelector("[data-part=\\"dropdown-panel\\"]"); if(sp) sp.setAttribute("hidden",""); }',
    '    dispatchPageEvent("selected", dsel ? dsel.getAttribute("data-entity")||"" : "", sel, { value: sel.getAttribute("data-value")||"" });',
    '  }',
    '});',
    'function closeAllDropdowns(except){',
    '  var all = document.querySelectorAll("[data-kind=\\"dropdown\\"],[data-kind=\\"menu\\"]");',
    '  for(var i=0;i<all.length;i++){',
    '    if(except && all[i].contains && all[i].contains(except)) continue;',
    '    all[i].setAttribute("data-open","false");',
    '    var p = all[i].querySelector("[data-part=\\"dropdown-panel\\"]");',
    '    if(p) p.setAttribute("hidden","");',
    '  }',
    '}',
    '// Tooltip: hover and keyboard focus show; leaving hides. Pure CSS handles the',
    '// visual; this only mirrors the state onto the host for CSS + events.',
    'document.addEventListener("mouseover", function(e){',
    '  var tip = e.target && e.target.closest ? e.target.closest("[data-kind=\\"tooltip\\"]") : null;',
    '  if(tip) tip.setAttribute("data-visible","true");',
    '});',
    'document.addEventListener("mouseout", function(e){',
    '  var tip = e.target && e.target.closest ? e.target.closest("[data-kind=\\"tooltip\\"]") : null;',
    '  if(tip && !(e.relatedTarget && tip.contains && tip.contains(e.relatedTarget))) tip.setAttribute("data-visible","false");',
    '});',
    'document.addEventListener("focusin", function(e){',
    '  var tip = e.target && e.target.closest ? e.target.closest("[data-kind=\\"tooltip\\"]") : null;',
    '  if(tip) tip.setAttribute("data-visible","true");',
    '});',
    'document.addEventListener("focusout", function(e){',
    '  var tip = e.target && e.target.closest ? e.target.closest("[data-kind=\\"tooltip\\"]") : null;',
    '  if(tip) tip.setAttribute("data-visible","false");',
    '});',
  ];
}
