/**
 * Table behaviors: client-side sort and pagination over the rendered tbody.
 *
 * Pure DOM over already-rendered rows — the compiler stamps the markup, these
 * drive it live. Split by page row visibility.
 */
export function tableBehaviors(): string[] {
  return [
    '// Sortable tables: click a sortable header to re-sort its tbody live.',
    'document.addEventListener("click", function(e){',
    '  var th = e.target && e.target.closest ? e.target.closest("th[data-sortable=\\"true\\"]") : null;',
    '  if(!th) return;',
    '  var table = th.closest("table");',
    '  if(!table || !table.tBodies || !table.tBodies[0]) return;',
    '  var idx = -1; var cells = th.parentNode ? th.parentNode.children : [];',
    '  for(var i=0;i<cells.length;i++){ if(cells[i]===th){idx=i;break;} }',
    '  if(idx<0) return;',
    '  var dir = th.getAttribute("data-sort-dir")==="asc" ? -1 : 1;',
    '  var heads = table.querySelectorAll("th[data-sortable]");',
    '  for(var h=0;h<heads.length;h++){ heads[h].removeAttribute("data-sort-dir"); var aw=heads[h].querySelector("[data-part=\\"sort-arrow\\"]"); if(aw) aw.textContent="\\u21C5"; }',
    '  th.setAttribute("data-sort-dir", dir===1?"asc":"desc");',
    '  var arrow = th.querySelector("[data-part=\\"sort-arrow\\"]");',
    '  if(arrow) arrow.textContent = dir===1?"\\u25B2":"\\u25BC";',
    '  var rows = Array.prototype.slice.call(table.tBodies[0].rows);',
    '  rows.sort(function(a,b){',
    '    var av=(a.cells[idx]?a.cells[idx].textContent:"").trim();',
    '    var bv=(b.cells[idx]?b.cells[idx].textContent:"").trim();',
    '    var an=parseFloat(av), bn=parseFloat(bv);',
    '    var cmp=(!isNaN(an)&&!isNaN(bn)) ? (an-bn) : (av<bv?-1:av>bv?1:0);',
    '    return cmp*dir;',
    '  });',
    '  for(var r=0;r<rows.length;r++){ table.tBodies[0].appendChild(rows[r]); }',
    '});',
    '// Table pagination: page buttons slice the static tbody rows live.',
    'document.addEventListener("click", function(e){',
    '  var btn = e.target && e.target.closest ? e.target.closest("[data-part=\\"pagination\\"] button[data-page]") : null;',
    '  if(!btn || btn.disabled) return;',
    '  var bar = btn.closest("[data-part=\\"pagination\\"]");',
    '  var wrap = bar ? (bar.previousElementSibling||bar.parentNode) : null;',
    '  var table = wrap ? (wrap.tagName==="TABLE"?wrap:wrap.querySelector("table")) : null;',
    '  if(!table || !table.tBodies || !table.tBodies[0]) return;',
    '  var rows = table.tBodies[0].rows;',
    '  var per = 0;',
    '  for(var i=0;i<rows.length;i++){ if(rows[i].style.display!=="none"){per++;} }',
    '  var total = rows.length;',
    '  var pages = Math.max(1, Math.ceil(total/Math.max(1,per||total)));',
    '  var cur = 1;',
    '  var curBtn = bar.querySelector("button[data-current=\\"true\\"]");',
    '  if(curBtn) cur = parseInt(curBtn.getAttribute("data-page")||"1",10)||1;',
    '  var want = btn.getAttribute("data-page");',
    '  var next = want==="prev" ? cur-1 : want==="next" ? cur+1 : parseInt(want||"1",10)||1;',
    '  next = Math.max(1, Math.min(pages, next));',
    '  var size = Math.max(1, Math.ceil(total/pages));',
    '  for(var r=0;r<rows.length;r++){ rows[r].style.display = (r>=((next-1)*size)&&r<(next*size))?"":"none"; }',
    '  var btns = bar.querySelectorAll("button[data-page]");',
    '  for(var b=0;b<btns.length;b++){',
    '    var p = btns[b].getAttribute("data-page");',
    '    if(p==="prev"){btns[b].disabled = next<=1;}',
    '    else if(p==="next"){btns[b].disabled = next>=pages;}',
    '    else if(btns[b].hasAttribute("data-current")||p===String(cur)){ if(p===String(next))btns[b].setAttribute("data-current","true");else btns[b].removeAttribute("data-current"); }',
    '  }',
    '});',
    '// Row selection: checkbox/radio marks the row and dispatches `selected`.',
    'document.addEventListener("change", function(e){',
    '  var box = e.target && e.target.closest ? e.target.closest("input[data-part=\\"select\\"]") : null;',
    '  if(!box) return;',
    '  var tr = box.closest("tr");',
    '  var table = box.closest("table");',
    '  if(!tr || !table) return;',
    '  tr.setAttribute("data-selected", box.checked ? "true" : "false");',
    '  if(table.getAttribute("data-select-mode")==="single" && box.checked){',
    '    var others = table.querySelectorAll("tbody input[data-part=\\"select\\"]:checked");',
    '    for(var o=0;o<others.length;o++){ if(others[o]!==box){ others[o].checked=false; var otr=others[o].closest("tr"); if(otr) otr.setAttribute("data-selected","false"); } }',
    '  }',
    '  var keys=[];',
    '  var now = table.querySelectorAll("tbody input[data-part=\\"select\\"]:checked");',
    '  for(var k=0;k<now.length;k++){ keys.push(now[k].getAttribute("data-key")||""); }',
    '  dispatchPageEvent("selected", table.getAttribute("data-entity")||"", tr, { keys: keys, key: box.getAttribute("data-key")||"", selected: box.checked });',
    '});',
    '// Page-size selector: re-slice the visible rows at the new size.',
    'document.addEventListener("change", function(e){',
    '  var sel = e.target && e.target.closest ? e.target.closest("select[data-page-size]") : null;',
    '  if(!sel) return;',
    '  var bar = sel.closest("[data-part=\\"pagination\\"]");',
    '  var wrap = bar ? (bar.previousElementSibling||bar.parentNode) : null;',
    '  var table = wrap ? (wrap.tagName==="TABLE"?wrap:wrap.querySelector("table")) : null;',
    '  if(!table || !table.tBodies || !table.tBodies[0]) return;',
    '  var rows = table.tBodies[0].rows;',
    '  var size = parseInt(sel.value||"10",10)||10;',
    '  for(var r=0;r<rows.length;r++){ rows[r].style.display = (r<size)?"":"none"; }',
    '  sel.setAttribute("data-page-size", String(size));',
    '  var curBtn = bar.querySelector("button[data-current=\\"true\\"]") || bar.querySelector("button[data-page=\\"1\\"]");',
    '  if(curBtn) curBtn.click();',
    '});',
  ];
}
