/**
 * Context assembly + action invocation + backend calls.
 */

export function actionsPart(): string[] {
  return [
    'function makeTheme(){return {',
    '  get:function(){var s=readState();return (s&&s.theme)||{mode:"light"};},',
    '  set:function(m){commitState("theme",function(root){root.theme={mode:m};});return {mode:m};},',
    '};}',
    '// The live ui (handles, pages, icons, dom) is the bundled runtime module;',
    '// this only supplies the state/event plumbing it shares with us.',
    'function makeRuntimeDeps(){',
    '  return {',
    '    readState:readState,',
    '    commitState:commitState,',
    '    subscribePath:subscribePath,',
    '    indexElement:indexElement,',
    '    forgetElement:forgetElement,',
    '    dispatchPageEvent:function(event,origin,el,payload){ dispatchPageEvent(event,origin,el,payload); },',
    // The bus transport (`window.__morgana_events`) lives in the same closure
    // as the page bus, not on `window`. It is handed to the runtime here rather
    // than read off the global so the runtime has no ambient window access —
    // and so tests can pass a stub instead of a real transport.
    '    __morgana_events: typeof __morgana_events!=="undefined" ? __morgana_events : undefined,',
    // The project/env query parameters every runtime call is scoped by. Read
    // from the same metas, so there is one answer to "which project is this
    // page?" rather than two.
    '    projectParams: function(){ return typeof __projectParams!=="undefined" ? __projectParams() : ""; },',
    '    withProject: function(p){ return typeof __withProject!=="undefined" ? __withProject(p) : p; },',
    '    runtimeHeaders: function(){ return typeof __runtimeHeaders!=="undefined" ? __runtimeHeaders() : { "Content-Type":"application/json" }; },',
    '    logEvent:logEvent,',
    '    makeTheme:makeTheme,',
    '    onPageEvent:onPageEvent,',
    '    navigate:function(url,opts){ if(typeof navigateSpa!=="undefined") navigateSpa(url,opts); else if(typeof location!=="undefined"&&location.assign) location.assign(url); },',
    '    dispatchPropChange:function(origin,prop,value,oldValue,el){ dispatchPropChange(origin,prop,value,oldValue,el); },',
    '  };',
    '}',
    'var __uiCache=null;',
    'function getUi(){',
    '  if(__uiCache) return __uiCache;',
    '  var rt=window.__morgana_runtime;',
    '  if(!rt||typeof rt.makeUi!=="function"){',
    '    throw new Error("[Morgana] page runtime missing — client.js was not built by @morgana/sdk-compile");',
    '  }',
    '  __uiCache=rt.makeUi(makeRuntimeDeps());',
    '  return __uiCache;',
    '}',
    '// The runtime key, read from the page. The worker injects it into every',
    '// served page, so a deployed bundle can reach its own backend without a',
    '// user session — and only its own project. Absent locally (server.mjs does',
    '// not check) or on a hand-served document, in which case no header is sent.',
    // The runtime key, read from the page. The worker injects it into every
    // served page, so a deployed bundle can reach its own backend without a
    // user session — and only its own project.
    //
    // `runtimeHeaders` itself is supplied by transport.ts, so the key and the
    // project params are read from the same place by the same code. Having a
    // second copy of this in the action part is how the two drifted.
    'function metaContent(name){',
    '  var el=document.querySelector(\'meta[name="\'+name+\'"]\');',
    '  return el?el.getAttribute("content")||"":"";',
    '}',
    '// Delegates to the transport so the runtime key is read in exactly one',
    '// place. Declared here as well because the error-log post below calls it',
    '// directly, and when it was supplied only through the deps object this name',
    '// was undefined — the ReferenceError was swallowed by that call own',
    '// try/catch and the error report silently went nowhere.',
    'function runtimeHeaders(){',
    '  if(typeof __runtimeHeaders!=="undefined") return __runtimeHeaders();',
    '  var h={"Content-Type":"application/json"};',
    '  var key=metaContent("morgana-runtime-key");',
    '  if(key) h["x-morgana-runtime"]=key;',
    '  return h;',
    '}',
    '// Which project/env this page belongs to. The worker injects both; without',
    '// them every action call would resolve to the worker\'s default project, so',
    '// two deployed projects would share (and overwrite) one another.',
    '// Delegates to __withProject (transport.ts) rather than building its own query',
    '// string. Two places answering "which project is this page?" is how a',
    '// second leading `?` got appended to a path that already had one, giving',
    '// /api/events?channel=lobby?projectId=… — a path the worker read as a',
    '// channel named "lobby?projectId=asy" and never matched.',
    'function projectQuery(){',
    '  // Delegated to the transport so there is one answer to "which project is',
    '  // this page?". Two places answering it is how a second leading "?" got',
    '  // appended to a path that already had one, giving',
    '  // /api/events?channel=lobby?projectId=… — which the worker read as a',
    '  // channel named "lobby?projectId=…" and never matched.',
    '  if(typeof __withProject!=="undefined") return __withProject("");',
    '  return "";',
    '}',
    'function makeActions(){',
    '  return {',
    '    run:function(aname,params){',
    '      return fetch("/api/actions/"+encodeURIComponent(aname)+"/run"+projectQuery(),{method:"POST",headers:runtimeHeaders(),body:JSON.stringify({params:params||{}})})',
    '      .then(function(r){',
    '        return r.json().catch(function(){return {};}).then(function(d){',
    '          // A 401 here is almost always a stale page: the key is minted per',
    '          // project, so a page held open across a key rotation 401s. Say so',
    '          // rather than surfacing a bare auth failure.',
    '          if(r.status===401||r.status===403){ throw new Error("[Morgana] "+aname+" was refused ("+r.status+") — this page is stale, reload it to pick up the current runtime key."); }',
    '          return d;',
    '        });',
    '      })',
    '      .then(function(d){if(d&&d.data&&typeof d.data==="object"&&d.data.result!==undefined)return d.data.result;return d&&d.data!==undefined?d.data:d;});',
    '    },',
    '  };',
    '}',
    '// Asset base, so ctx.assets.url() resolves wherever the page was served from.',
    '// Locally that is /assets; deployed, the worker rewrites the meta tag to',
    '// its env-scoped route so both resolve identically.',
    'function assetBase(){',
    '  var meta = document.querySelector(\'meta[name="morgana-asset-base"]\');',
    '  var v = meta ? meta.getAttribute("content") : "";',
    '  return (v && v.charAt(v.length-1)==="/") ? v.slice(0,-1) : (v || "/assets");',
    '}',
    'function makeAssets(){',
    '  return {',
    '    url:function(n){ var b=assetBase(); var s=String(n||""); return s.charAt(0)==="/" ? b+"/"+s.replace(/^\\/+/,"") : b+"/"+s; },',
    '    // A browser action cannot read the asset store directly; it resolves URLs',
    '    // and lets the browser fetch. Declared by BaseContext, absent before.',
    '    get:function(n){ return fetch(assetBase()+"/"+String(n||"").replace(/^\\/+/,"")).then(function(r){ return r.ok ? r.text() : null; }).catch(function(){ return null; }); },',
    '  };',
    '}',
    '// Server-lane surfaces on a browser action. Previously these keys were',
    '// absent, so calling them produced "undefined is not an object". A named',
    '// error says exactly why, which is the difference between a typo and a',
    '// misunderstanding of the lane.',
    'function serverOnly(name){',
    '  return function(){ throw new Error("[Morgana] ctx."+name+" is server-lane only — call it from a server action, not a browser action"); };',
    '}',
    'function makeCtx(triggerCtx,params){',
    '  var ui = getUi();',
    '  return { args:(params||{}), event:(triggerCtx||{name:"direct",origin:"",element:null,payload:{},timestamp:Date.now()}),',
    '    getState:function(){return readState();},',
    '    setState:function(next){return ui.setState(next);},',
    '    state:ui.state,',
    '    theme:ui.theme,',
    '    getTheme:function(){return ui.getTheme();},',
    '    setTheme:function(m){return ui.setTheme(m);},',
    '    ui:ui,',
    '    // Declared on ClientContext but previously missing from the built ctx.',
    '    libraries:ui.libraries,',
    '    apps:ui.apps,',
    '    vars:ui.vars,',
    '    assets:makeAssets(),',
    '    events:ui.events,',
    // Alias for `ctx.events.channels` — the same object, not a second
    // implementation. `ui.events.channels` carries subscribe/attach, which is
    // what a browser lane actually needs, so the short name points at exactly
    // that rather than at a parallel surface that has to be kept in step.
    '    channels:(ui.events && ui.events.channels) ? ui.events.channels : {},',
    '    log:function(){ var parts=Array.prototype.slice.call(arguments).map(String); logEvent({lane:"action",name:"log",message:parts.join(" ")}); if(typeof console!=="undefined") console.log.apply(console,parts); },',
    '    auth:serverOnly("auth"),',
    '    ai:serverOnly("ai"),',
    '    server:serverOnly("server"),',
    '    actions:makeActions() };',
    '}',
    'window.__morgana_run = function(name, params, triggerCtx){',
    '  var fn = window.__morgana_actions[name];',
    '  if(!fn) return Promise.reject(new Error("unknown action: "+name));',
    '  var trig = triggerCtx||{name:"direct",origin:"",element:null,payload:{},timestamp:Date.now()};',
    '  logEvent({lane:"action",name:"action:start",origin:name,trigger:trig.name});',
    '  dispatchPageEvent("action:start", name, null, {action:name,trigger:trig.name});',
    '  var t0 = Date.now();',
    '  function done(ok, result, error){',
    '    var ev = ok?"action:success":"action:error";',
    '    logEvent({lane:"action",name:ev,origin:name,duration:Date.now()-t0,error:error?String((error&&error.message)||error):undefined});',
    '    dispatchPageEvent(ev, name, null, {action:name,result:ok?result:undefined,error:error?String((error&&error.message)||error):undefined,duration:Date.now()-t0});',
    '    if(!ok){ try{ fetch("/api/events/log",{method:"POST",headers:runtimeHeaders(),body:JSON.stringify({event:ev,source:name,error:String((error&&error.message)||error)})}).catch(function(){}); }catch(e){} }',
    '  }',
    '  try{',
    '    var ctx=makeCtx(trig,params||{});',
    '    return Promise.resolve(fn(ctx, params||{})).then(function(result){ done(true,result); return result; }, function(err){ done(false,undefined,err); throw err; });',
    '  }catch(err){ done(false,undefined,err); return Promise.reject(err); }',
    '};',
  ];
}
