/**
 * Binding table + page/state dispatch.
 */

export function busPart(bindingsJson: string): string[] {
  return [
    '// Page-level bindings from browser action `on` selectors (frontend events).',
    'var __bindings = ' + bindingsJson + ';',
    '// Event log: every dispatch appends {ts, lane, name, origin}. Ring buffer.',
    'var __eventLog=[];',
    'function logEvent(entry){entry.ts=Date.now();__eventLog.push(entry);if(__eventLog.length>200)__eventLog.shift();return entry;}',
    '// The ring buffer was maintained but never read, so ui.events.getLog()',
    '// returned [] while real entries sat unread. Exposed by name.',
    'function getEventLog(filter){',
    '  if(!filter) return __eventLog.slice();',
    '  if(typeof filter==="string") return __eventLog.filter(function(e){ return e.name===filter; });',
    '  if(filter.name) return __eventLog.filter(function(e){ return e.name===filter.name; });',
    '  if(filter.lane) return __eventLog.filter(function(e){ return e.lane===filter.lane; });',
    '  return __eventLog.slice();',
    '}',
    'function getEventSources(){',
    '  var seen={};var out=[];',
    '  for(var i=0;i<__bindings.length;i++){ var b=__bindings[i]; if(!b||!b.event) continue; if(seen[b.event]) continue; seen[b.event]=1; out.push({name:b.event, action:b.action, lane:"page"}); }',
    '  return out;',
    '}',
    '// State subscriptions from `on: "state:<path>"` — fire the action with the',
    '// change descriptor whenever the watched path (or its parent/children) moves.',
    '// Live-handle subscribers: `handle.when(event, fn)` on a page object.',
    'var __pageSubs=[];',
    'function onPageEvent(fn){ __pageSubs.push(fn); return function(){ var i=__pageSubs.indexOf(fn); if(i>=0)__pageSubs.splice(i,1); }; }',
    'function dispatchStateEvent(path,value,oldValue){',
    '  for(var i=0;i<__bindings.length;i++){',
    '    var b=__bindings[i];',
    '    if(!b||!b.event||b.event.indexOf("state:")!==0)continue;',
    '    var watched=b.event.slice(6);',
    '    if(!pathOverlaps(watched,path))continue;',
    '    logEvent({lane:"state",name:b.event,origin:"state",path:path});',
    '    window.__morgana_run(b.action,{}, {name:b.event,origin:"state",element:null,payload:{path:path,value:value,oldValue:oldValue},timestamp:Date.now()});',
    '  }',
    '}',
    'function dispatchPageEvent(event, target, el, raw){',
    '  logEvent({lane:"page",name:event,origin:target||""});',
    '  var subs=__pageSubs.slice();',
    '  for(var s=0;s<subs.length;s++){ try{ subs[s](event,target||"",el||null,raw||{}); }catch(e){ console.error("[Morgana] page subscriber failed:",e); } }',
    '  for(var i=0;i<__bindings.length;i++){',
    '    var b = __bindings[i];',
    '    if(b.event !== event) continue;',
    '    // A binding may be scoped to one object, and to one prop of it.',
    '    if(b.origin && b.origin !== (target||"")) continue;',
    '    if(b.prop){',
    '      var p = raw && raw.prop;',
    '      if(p !== b.prop) continue;',
    '    }',
    '    window.__morgana_run(b.action, {}, {name:event,origin:target||"",element:el||null,payload:raw||{},timestamp:Date.now()});',
    '  }',
    '}',
    '// Prop mutation: a binding on `object.prop.changed`. Emitted by set(), so',
    '// it is a real change to the object rather than something tied to state —',
    '// `set("label", x)` fires it whether or not a bind() is watching.',
    'function dispatchPropChange(target, prop, value, oldValue, el){',
    '  dispatchPageEvent("prop:changed", target, el, { prop: prop, value: value, oldValue: oldValue });',
    '}',
  ];
}
