/**
 * Reactive state: store, subscriptions, commits.
 */

export function statePart(): string[] {
  return [
    'function readState(){try{var el=document.getElementById("__MORGANA_STATE__");return el?JSON.parse(el.textContent||"{}"):{};}catch(e){return {};}}',
    'function writeState(next){var el=document.getElementById("__MORGANA_STATE__");if(el) el.textContent=JSON.stringify(next);return next;}',
    'function getPath(root,path){if(!path)return root;var cur=root;var parts=String(path).split(".");for(var i=0;i<parts.length;i++){if(cur==null)return undefined;cur=cur[parts[i]];}return cur;}',
    'function setPath(root,path,value){var parts=String(path).split(".");var cur=root;for(var i=0;i<parts.length-1;i++){var p=parts[i];if(typeof cur[p]!=="object"||cur[p]===null)cur[p]={};cur=cur[p];}cur[parts[parts.length-1]]=value;return root;}',
    'function sameValue(a,b){try{return JSON.stringify(a)===JSON.stringify(b);}catch(e){return a===b;}}',
    '// Reactive state: subscribers fire on the paths they watch (exact path or',
    '// any parent/child overlap), receiving (path, value, oldValue, root).',
    'var __stateSubs=[];',
    // Derived-prop re-evaluation. A Resolver function (sdk/handles.ts) is
    // re-run whenever state changes, so a prop computed from another object
    // stays live instead of freezing at the value it had when it was set.
    'var __derivedHooks=[];',
    'function registerDerivedHook(fn){__derivedHooks.push(fn);return function(){var i=__derivedHooks.indexOf(fn);if(i>=0)__derivedHooks.splice(i,1);};}',
    'function pathOverlaps(a,b){if(a===""||b==="")return true;return a===b||a.indexOf(b+".")===0||b.indexOf(a+".")===0;}',
    'function notifyState(path,value,oldValue,root){',
    '  dispatchStateEvent(path,value,oldValue);',
    '  for(var d=0;d<__derivedHooks.length;d++){',
    '    try{ __derivedHooks[d](); }catch(e){ console.error("[Morgana] derived prop failed:",e); }',
    '  }',
    '  var subs=__stateSubs.slice();',
    '  for(var i=0;i<subs.length;i++){',
    '    try{',
    '      if(pathOverlaps(subs[i].path,path)) subs[i].fn(path,value,oldValue,root);',
    '    }catch(e){console.error("[Morgana] state subscriber failed:",e);}',
    '  }',
    '}',
    'function commitState(path,mut){',
    '  var root=readState();',
    '  var oldValue=getPath(root,path);',
    '  mut(root);',
    '  var next=writeState(root);',
    '  var value=getPath(next,path);',
    '  if(!sameValue(value,oldValue)) notifyState(path,value,oldValue,next);',
    '  return next;',
    '}',
    'function subscribePath(path,fn){',
    '  var entry={path:path,fn:fn};',
    '  __stateSubs.push(entry);',
    '  return function(){var i=__stateSubs.indexOf(entry);if(i>=0)__stateSubs.splice(i,1);};',
    '}',
    'function makeState(){return {',
    '  get:function(p){return getPath(readState(),p);},',
    '  set:function(p,v){return commitState(p,function(root){setPath(root,p,v);});},',
    '  append:function(p,item){return commitState(p,function(root){var cur=getPath(root,p);var arr=Array.isArray(cur)?cur.slice():[];arr.push(item);setPath(root,p,arr);});},',
    '  remove:function(p){return commitState(p,function(root){var parts=String(p).split(".");var cur=root;for(var i=0;i<parts.length-1;i++){cur=cur?cur[parts[i]]:undefined;}if(cur)delete cur[parts[parts.length-1]];});},',
    '  getAll:function(){return readState();},',
    '  subscribe:function(listener){return subscribePath("",listener);},',
    '};}',
    '// Live DOM bindings: elements carrying data-bind="prop:source;..." re-render',
    '// from state whenever a watched path changes. Sources resolve against the',
    '// state root, so bind("cart.count") follows state.cart.count.',
    '//',
    '// Bound elements are indexed once and each entry subscribes to its own',
    '// path, so a commit costs only the records that actually moved — not a',
    '// querySelectorAll plus a spec re-parse of the whole page. Elements added',
    '// later (repeat rows) register through indexElement.',
    'function writeBinding(el,prop,value){',
    '  if(value===undefined||value===null)return;',
    '  var s=String(value);',
    '  if(prop==="*"||prop==="content"||prop==="label"||prop==="text"){',
    '    if(el.tagName==="INPUT"||el.tagName==="TEXTAREA"||el.tagName==="SELECT"){el.value=s;}',
    '    else{el.textContent=s;}',
    '  }',
    '  else if(prop==="value"){if("value" in el)el.value=s;else el.textContent=s;}',
    '  else if(prop==="src"||prop==="href"||prop==="alt"){el.setAttribute(prop,s);}',
    '  else{el.setAttribute("data-prop-"+prop,s);}',
    '}',
    'function readBindSpec(el){',
    '  var spec=el.getAttribute?el.getAttribute("data-bind"):null;',
    '  if(!spec)return [];',
    '  var out=[];',
    '  var parts=spec.split(";");',
    '  for(var i=0;i<parts.length;i++){',
    '    var kv=parts[i].split(":");',
    '    if(kv.length<2)continue;',
    '    out.push({el:el,prop:kv[0],source:kv.slice(1).join(":")});',
    '  }',
    '  return out;',
    '}',
    'var __bindRecs=[];',
    'var __bindUnsubs=[];',
    'function indexElement(el){',
    '  var recs=readBindSpec(el);',
    '  if(!recs.length)return 0;',
    '  var root=readState();',
    '  for(var i=0;i<recs.length;i++){',
    '    var rec=recs[i];',
    '    __bindRecs.push(rec);',
    '    // Take the current value on the way in, so a freshly mounted row is',
    '    // painted without waiting for the next change.',
    '    writeBinding(rec.el,rec.prop,getPath(root,rec.source));',
    '    __bindUnsubs.push((function(r){',
    '      // Re-read this binding\'s own source from the root rather than using',
    '      // the changed value: a parent binding (":cart") must take the whole',
    '      // object when a child path (cart.label) is what moved.',
    '      return subscribePath(r.source,function(path,value,oldValue,root){',
    '        writeBinding(r.el,r.prop,getPath(root,r.source));',
    '      });',
    '    })(rec));',
    '  }',
    '  return recs.length;',
    '}',
    'function forgetElement(el){',
    '  for(var i=__bindRecs.length-1;i>=0;i--){',
    '    if(__bindRecs[i].el!==el)continue;',
    '    var unsub=__bindUnsubs[i];',
    '    if(unsub)unsub();',
    '    __bindRecs.splice(i,1);',
    '    __bindUnsubs.splice(i,1);',
    '  }',
    '}',
    'function indexRoot(){',
    '  var els=document.querySelectorAll?document.querySelectorAll("[data-bind]"):[];',
    '  var n=0;',
    '  for(var i=0;i<els.length;i++) n+=indexElement(els[i]);',
    '  return n;',
    '}',
    '// First paint: every bound element takes its initial value once.',
    'function paintAllBindings(){',
    '  var root=readState();',
    '  for(var i=0;i<__bindRecs.length;i++){',
    '    var rec=__bindRecs[i];',
    '    writeBinding(rec.el,rec.prop,getPath(root,rec.source));',
    '  }',
    '}',
    '// Retained for callers outside the runtime that want a one-shot re-read.',
    'function applyBindings(){ paintAllBindings(); }',
  ];
}
