/**
 * Stylesheet assembly: base rules, per-entity, parts, breakpoints.
 */
import { buildStyleCtx, cssDeclsToString, resolvePropsToCss } from './props';
import { resolvePartStyles } from './parts';
import { animationClasses, animationKeyframes } from '../compile-ctx/tokens';
import type { ProjectIR } from '../ir';

/** CSS for the animation and behavior words `make()` can set. */
function tokenClassRules(ir: ProjectIR): string[] {
  const used = new Set<string>()
  for (const node of ir.objects.values()) {
    const a = node.props['animate']
    if (typeof a === 'string') used.add(`morgana-anim-${a.replace(/-/g, '_')}`)
    const b = node.props['behavior']
    if (typeof b === 'string') used.add(`morgana-bh-${b}`)
  }
  if (!used.size) return []
  const all = animationClasses()
  const out: string[] = []
  for (const cls of used) {
    const decls = all[cls]
    if (decls) out.push(`.${cls}{${decls}}`)
  }
  return out
}

export function renderStyleCss(ir: ProjectIR): string {
  const ctx = buildStyleCtx(ir)
  const skeletonUses = [...ir.objects.values()].some(
    (n) => n.kind === 'skeleton' && n.props['animate'] !== false,
  )
  const lines: string[] = [
    '/* generated by @morgana/sdk-compile */',
    '*{box-sizing:border-box}',
    ':root{--background:#ffffff;--foreground:#18181B;--card:#ffffff;--card-foreground:#18181B;--muted:#F4F4F5;--muted-foreground:#71717A;--border:#E4E4E7;--primary:#18181B;--primary-foreground:#FAFAFA;--shadow:0 1px 3px 0 rgba(0, 0, 0, 0.1), 0 1px 2px -1px rgba(0, 0, 0, 0.1)}',
    'body{margin:0;font-family:system-ui,-apple-system,sans-serif;background:var(--background);color:var(--foreground)}',
    '[data-part="icon"]{display:inline-flex;align-items:center;justify-content:center;flex:none}',
    // An icon whose library loads deferred must still occupy its box, or the
    // swap from empty placeholder to svg nudges the line it sits on. Reserve
    // the same 1.25em the rendered svg gets.
    '[data-part="icon"]:empty,[data-part="icon"]>i:empty{min-width:1.25em;min-height:1.25em}',
    '[data-part="icon"] svg{width:1.25em;height:1.25em}',
    '[data-part="icon"] img{width:1.25em;height:1.25em;object-fit:contain}',
    '[data-kind="button"]:has([data-part="icon"]){display:inline-flex;align-items:center;gap:8px}',
    'th[data-align="center"],td[data-align="center"]{text-align:center}',
    'th[data-align="right"],td[data-align="right"]{text-align:right}',
    'th[data-align="left"],td[data-align="left"]{text-align:left}',
    '[data-kind="dialog"]{position:fixed;inset:0;z-index:50;display:flex;align-items:center;justify-content:center}',
    '[data-part="pagination"]{display:flex;align-items:center;justify-content:center;gap:8px;padding:12px 0}',
    '[data-part="pagination"] button{cursor:pointer;border:1px solid var(--border);background:var(--card);border-radius:6px;padding:4px 10px}',
    '[data-part="pagination"] button[data-current="true"]{background:var(--primary);color:var(--primary-foreground);border-color:transparent}',
    '[data-part="fill"][data-striped="true"]{background-image:repeating-linear-gradient(45deg,rgba(255,255,255,.25) 0 8px,transparent 8px 16px)}',
    '[data-part="fill"][data-animated="true"]{animation:morgana-progress 1s linear infinite}',
    '@keyframes morgana-progress{from{background-position:0 0}to{background-position:22px 0}}',
    '[data-part="error"]{color:#DC2626;font-size:12px;margin-top:4px}',
    '[data-part="tab-badge"]{font-size:11px;background:var(--muted);color:var(--foreground);border-radius:9999px;padding:0 6px;margin-left:6px}',
    '[data-part="cell-badge"]{display:inline-block;background:var(--muted);border-radius:9999px;padding:2px 8px;font-size:12px}',
    '[data-part="cell-bar"]{display:block;background:var(--muted);border-radius:9999px;height:8px;min-width:80px;overflow:hidden}',
    '[data-part="cell-fill"]{display:block;height:100%;background:var(--primary);border-radius:inherit}',
    '[data-part="overlay"]{cursor:default}',
  ]
  // Animation + behavior classes, and the keyframes they reference.
  lines.push(...tokenClassRules(ir))
  const needsKeyframes = skeletonUses || tokenClassRules(ir).length > 0
  if (needsKeyframes) lines.push(animationKeyframes())
  for (const [name, value] of ir.measures) {
    lines.push(`:root{--m-${name}:${typeof value === 'number' ? `${value * 4}px` : String(value)}}`)
  }
  for (const node of ir.objects.values()) {
    if (node.kind === 'page') continue
    const css = resolvePropsToCss(node.props as Record<string, unknown>, node.kind, ctx)
    const decls = cssDeclsToString(css)
    if (decls) lines.push(`[data-entity="${node.id}"]{${decls}}`)
    for (const rule of resolvePartStyles(node.kind, node.id, node.props as Record<string, unknown>, ctx)) {
      const partDecls = cssDeclsToString(rule.css)
      if (partDecls) lines.push(`${rule.selector}{${partDecls}}`)
    }
  }
  const mediaQuery = (bp: string): string | null => {
    const shape = ir.breakpoints.get(bp)
    if (!shape) return null
    const conds: string[] = []
    if (typeof shape.minWidth === 'number') conds.push(`(min-width:${shape.minWidth}px)`)
    if (typeof shape.maxWidth === 'number') conds.push(`(max-width:${shape.maxWidth}px)`)
    return conds.length ? conds.join(' and ') : null
  }
  for (const node of ir.objects.values()) {
    for (const [bp, props] of Object.entries(node.breakpointProps)) {
      const query = mediaQuery(bp)
      if (!query) continue
      const css = resolvePropsToCss(props as Record<string, unknown>, node.kind, ctx)
      const decls = cssDeclsToString(css)
      if (!decls) continue
      lines.push(`@media ${query}{[data-entity="${node.id}"]{${decls}}}`)
    }
  }
  lines.push('')
  return lines.join('\n')
}

/** Strip types from a handler snippet with the real TS compiler. */
